# Generated by Django 4.0.1 on 2022-02-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='espera', max_length=15, verbose_name="cart's state")),
                ('created_at', models.DateField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="user's ID")),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name="product's name")),
                ('price', models.IntegerField(verbose_name='price')),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='ecommerce.Category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Cart_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('id_cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.cart', verbose_name='Cart ID')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product', verbose_name='Product ID')),
            ],
            options={
                'verbose_name': 'cart_product',
                'verbose_name_plural': 'cart_products',
            },
        ),
    ]
