# Generated by Django 4.0.1 on 2022-02-14 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{1,14}$', 'phone number in the format ')]),
        ),
    ]
